### ISSUE TITLE
Remote Linux Server

### ISSUE THREAD

**Issue by BU-1** [topepo/par-caret-bench#1]
Thanks for the helpful post, really great overview of how to utilize parallel processing with `caret`. 

I'm having some issues training models in parallel on a remote Linux server. When I use serial processing, my model takes about 5 seconds to train, but when I run in parallel (I've tried forking and sockets), my model takes about 75 seconds to train. Any initial ideas as to what the problem might be?

**Comment by topepo** [comment]
Without knowing any details, I have no idea.

**Comment by BU-1** [comment]
@topepo here is an example of the issue I'm running into.

This script trains a simple model using xgboost and iris data.
[train_generic.txt](https://github.com/topepo/par-caret-bench/files/2665408/train_generic.txt)

This script runs the script sequentially and then in parallel with 6 workers
[compare_seq_par.txt](https://github.com/topepo/par-caret-bench/files/2665410/compare_seq_par.txt)

When I ran compare_seq_par from my Windows desktop the model took 3.11 seconds to train sequentially and 6.84 seconds to train in parallel (console results below, including session info).
[results_desktop.txt](https://github.com/topepo/par-caret-bench/files/2665416/results_desktop.txt)

When I ran compare_seq_par from my remote Linux server (from RStudio Server) the model took 3.07 seconds to train sequentially and 70.25 seconds to train in parallel.
[results_server.txt](https://github.com/topepo/par-caret-bench/files/2665425/results_server.txt)

**Comment by BU-1** [comment]
@topepo I believe I may have stumbled upon the issue. Parallel performance is much faster when I specify `nthread = 1` in `caret::train()`.
